# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb5015188dfdd8f8de07415124d2fe8004fad1d02ff74d7ad2c262a7dedf45080305204a057ed60cf135365f45cb42d4c0502e5b0afb5c864ee2ceb8e2e0160f

test:
  secret_key_base: 0751ecad9b91681794c9485dda3a40c347967b5647ab8f902f8cab1960120c96dd01f8a6d5cc87e1dd312def424ab96c7afe8047f7c4d41cb97e3b326496aecc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
